### PR TITLE
Feat decks with shared parameters

### PR DESCRIPTION
**Pull request by MNastri**
This adds `const decks_with_shared_config` as a new attribute in the configuration.
Users can set decks that share the same configuration instead of adding the same configuration multiple times.
The configuration name should be added to `deckParams` as a placeholder for it to work.
The code will create the proper deck names inside deckParams and remove the placeholder.

This is useful to me because I have several scattered decks that share the same config and, instead of adding each one of them in deckParams, I can just add their name to this new const. 
I don't know how useful this is to others but I hope it is

### CODE REVIEW

**Comment by MNastri** [comment]
[related PR](https://github.com/open-spaced-repetition/fsrs4anki-helper/pull/47)

**Comment by L-M-Sherlock** [comment]
I need some users to test it.

**Comment by MNastri** [comment]
Just reverted the change from `const` to `var` because it isn't needed

**Comment by L-M-Sherlock** [comment]
I have a question. How do you generate the same parameters for some decks without the same parent deck?

**Comment by MNastri** [comment]
I don't generate the parameters for these decks. 
I have these weights `"w": [1, 1, 5, -1, -1, 0.1, -0.9162, 0, 6.9314, 0.5, 0, 1, 0],`  for 'exposition' decks. 
These are usually things I want to keep seeing from time to time but don't want to commit to memory like ideas I think might be useful someday, long texts, inspiring quotes, exposition to good stories and stuff like that...

The weights halve the interval when I fail (meaning show me this more often) and go from 1.4 to 5.0 times the interval when I press good (meaning show me this less often)

But when I update my 'global config for fsrs4ank' weights I just rename the decks to remove them from the scope. I put some prefix like '_' before the name and they all get separated from my actual revision cards. After calibrating the weights I just rename the decks again removing the prefix.

**Comment by L-M-Sherlock** [comment]
Dae proposes the plan to integrate FSRS into Anki: https://github.com/ankitects/anki/issues/2443

I think the current PR would be helpful if we store the parameters in deck configs.

**Comment by L-M-Sherlock** [comment]
Sorry for my delayed reply. I found that many users didn't understand how to configure deck-specific parameters. So decks with shared parameters would be more complicated to them. Maybe integrating to Anki and configuring FSRS parameters in deck options is the best solution. So I will close this PR.

**Pull request closed without merging**
