### PR TITLE
Recommend sorting by relative overdueness.md

### PR DESCRIPTION
**Pull request by Expertium**
I think it's a good idea to recommend users to sort by Relative overdueness. I think people who use FSRS would like to see cards with the lowest R first.

### CODE REVIEW

**Comment by L-M-Sherlock** [comment]
But it's demotivating for those users who have a large backlog.

https://refold.la/roadmap/stage-1/c/srs-best-practices#Falling-Behind

**Comment by Expertium** [comment]
It's _especially_ useful if you have a backlog, because it prioritizes "saving" knowledge that is on the verge of forgetting.

**Comment by user1823** [comment]
In my opinion, the `Relative Overdueness` order should be used ONLY when you have a backlog. 

When the backlog is not there (or there is a small backlog), the `Random` order is preferable.
Reason: According to several studies, interlacing different materials increases the benefit of spaced repetition and the `Random` order is most likely to cause effective interlacing.

**Comment by L-M-Sherlock** [comment]
It's frustrating to review a lot of cards with low R consistently. And it also cannot maximize the knowledge acquisition. We can design a simulation to validate it.

**Comment by Expertium** [comment]
IMO not sorting by retrievability when you have an algorithm that is good at calculating retrievability feels like a waste. But I'm fine with your guys' decision to include/not include it in the manual either way.

**Comment by user1823** [comment]
So, should this PR be closed?

**Comment by Expertium** [comment]
I think it should be merged. Since you and I disagree, the final decision is up to LMSherlock.

**Comment by L-M-Sherlock** [comment]
Please see this simulation: https://github.com/open-spaced-repetition/review-sort-order-comparison/blob/main/notebook.ipynb

The simulation results show that `retrievability_desc` is the most efficient review sort order.

```
review sorting order: retrievability_asc
learned cards: 20000
time in minutes: 38966.6
remembered cards: 13710
time per remembered card: 2.84

review sorting order: retrievability_desc
learned cards: 20000
time in minutes: 30387.8
remembered cards: 13384
time per remembered card: 2.27

review sorting order: random
learned cards: 20000
time in minutes: 39464.3
remembered cards: 13692
time per remembered card: 2.88
```

**Comment by Expertium** [comment]
Interesting! Then, perhaps, we should ask @dae to implement that in Anki?

**Comment by L-M-Sherlock** [comment]
> Also, if I understand it correctly, sorting order matters only if the user has a limited amount of studying time per day, right?

The sorting order only matters when user cannot complete the backlog. In the simulation, I set a limit to `Maximum reviews/day` to simulate that case.

**Comment by L-M-Sherlock** [comment]
I add more sort orders into the simulation. The results show that `difficulty_asc` is the best. So I close this PR.

```
review sorting order: due_date_asc
learned cards: 20000
time in minutes: 41987.4
remembered cards: 13859
time per remembered card: 3.03

review sorting order: interval_asc
learned cards: 20000
time in minutes: 30455.2
remembered cards: 11971
time per remembered card: 2.54

review sorting order: interval_desc
learned cards: 20000
time in minutes: 32087.7
remembered cards: 11170
time per remembered card: 2.87

review sorting order: difficulty_asc
learned cards: 20000
time in minutes: 30552.4
remembered cards: 14114
time per remembered card: 2.16

review sorting order: difficulty_desc
learned cards: 20000
time in minutes: 30870.5
remembered cards: 10550
time per remembered card: 2.93

review sorting order: retrievability_asc
learned cards: 20000
time in minutes: 38966.6
remembered cards: 13710
time per remembered card: 2.84

review sorting order: retrievability_desc
learned cards: 20000
time in minutes: 30387.8
remembered cards: 13384
time per remembered card: 2.27

review sorting order: random
learned cards: 20000
time in minutes: 39464.3
remembered cards: 13692
time per remembered card: 2.88

review sorting order: add_order_asc
learned cards: 20000
time in minutes: 32541.1
remembered cards: 11130
time per remembered card: 2.92

review sorting order: add_order_desc
learned cards: 20000
time in minutes: 30431.9
remembered cards: 12757
time per remembered card: 2.39
```

**Comment by user1823** [comment]
@Expertium, you made this commit in a branch in `open-spaced-repetition/fsrs4anki`. For future PRs, it would be better to add commits to a new branch in your own fork of the repo.

**Comment by RogueArt** [comment]
Digesting/analyzing the results for anyone else viewing this thread:

**Results of above simulation:**
| Review Sorting Order        | Time in Minutes | Remembered Cards | Time per Remembered Card |
|-----------------------------|-----------------|------------------|--------------------------|
| Difficulty Ascending        | 30552.4         | 14114            | 2.16                     |
| Retrievability Descending   | 30387.8         | 13384            | 2.27                     |
| Add Order Descending        | 30431.9         | 12757            | 2.39                     |
| Interval Ascending          | 30455.2         | 11971            | 2.54                     |
| Retrievability Ascending    | 38966.6         | 13710            | 2.84                     |
| Interval Descending         | 32087.7         | 11170            | 2.87                     |
| Random                      | 39464.3         | 13692            | 2.88                     |
| Add Order Ascending         | 32541.1         | 11130            | 2.92                     |
| Difficulty Descending       | 30870.5         | 10550            | 2.93                     |
| Due Date Ascending          | 41987.4         | 13859            | 3.03                     |

Reading the above simulation code @L-M-Sherlock added, **this assumes we are only covering a total of 80 reviews per day** and no more in a contiguous block and so for a time-limited user, then difficulty ascending is the best. However, if you're doing all your reviews every day (there is no review cap), then this simulation will indicate that all approaches are equally good

Thinking about these results, this makes sense intuitively because if you're not doing all the reviews every day, then it makes sense to prioritize cards you'd spend the least time on and are also be able to delay forgetting the longest, which are the easiest cards. This would let you cover the most amount of information given either a set amount of time or set amount of reviews.

**Comment by RogueArt** [comment]
**Opinion - I have no evidence to back this up. This is just me writing down my thoughts:**
Let's say that a user does all reviews, I would argue intuitively that the assumption that all approaches are equally good falls apart. I would actually argue, if you plan to do every review, every day, then the **difficulty descending order** or any order with "soonest/easiest to forget first" would be more effective, especially if it's combined with doing multiple sessions. This is because it'd allow the user to take advantage of the spacing effect within the day.

Here's the example that I came up with:
>  
> For example, say I have 100 cards to review and say I review in 3 sessions throughout the day:
> - At 10 AM, I review 20 and say I have a 50% chance of getting these ones wrong, then I will get 10 wrong
> - Then at 4 PM, I review another 30, but these cards have a 20% chance of being "Again", then I will get 6 wrong
> - Then at 10 PM, I review the rest, and these remaining cards have a 5% chance of being "Again"
> What happens is that the first 20 cards, which are the hardest, will then be reviewed at 4 PM, and 10 PM again. This means that I get that spacing effect multiple times *within* the day. If we did the opposite order, I'll run into the hardest cards last, so the spacing effect might only be 10:00 PM, 10:10 PM, 10:15 PM which are much shorter intervals.

I have no idea how to simulate this, but I just wanted to share my thoughts on this for anyone looking to optimize their time spent on Anki and might interpret the above results to say "oh difficulty ascending is the best, no question," which may not be the case for you. 

Oh and feel free to correct or point any mistakes with my logic. If I'm wrong, that's great because I can switch my ordering and I can save more time on Anki!

**Comment by L-M-Sherlock** [comment]
It's really hard to simulate it, because FSRS doesn't consider the interday learning. If you want to discuss it more, please open an new issue.

**Comment by Expertium** [comment]
@L-M-Sherlock can you test Stability Ascending and Stability Descending, too?

**Pull request closed without merging**
