### PR TITLE
Added a fancy chart.md

### PR DESCRIPTION
**Pull request by Expertium**
It illustrates how workload changes with retention.

### CODE REVIEW

**Comment by L-M-Sherlock** [comment]
I think it would be better:

image

**Comment by Expertium** [comment]
I was using 1/interval to approximate the workload. If you want to take into account the fact that for lower retention, worklaod icnreases due to the user having to relearn more forgotten cards, then this probably will require using the simulator to make an accurate chart.

**Comment by L-M-Sherlock** [comment]
OK. I will draw one with simulator.

**Comment by Vilhelm-Ian** [comment]
I don't get this chart. The optimizer gives different values for a smaller workload

**Comment by Expertium** [comment]
> I don't get this chart. The optimizer gives different values for a smaller workload

As I said, I was just using 1/interval. This takes into account how intervals themselves changes, but doesn't take into account the fact that as intervals become shorter, the user has to re-learn more.

**Comment by L-M-Sherlock** [comment]
image

```python
R = range(60, 98)
cost_per_memorization = [118.46067691245344,
 117.996435848432,
 116.9026381695129,
 116.90439453733136,
 117.0676543398416,
 116.87291721228723,
 116.31486268004336,
 115.85366389346582,
 116.4216439101658,
 115.19567302651005,
 114.87530852659273,
 113.53655325213391,
 115.13691533864515,
 115.62138703770871,
 114.76960076774199,
 115.40369340768487,
 115.82480378468483,
 114.9575330411633,
 116.94736342126731,
 117.58531651606509,
 117.36775574433011,
 119.32339071100732,
 120.45015145509191,
 122.19685831432899,
 124.6350740547518,
 126.99968537807649,
 129.70336675687713,
 132.41933601503496,
 136.80095507331478,
 142.44879085247103,
 148.0477921109703,
 157.41139358191,
 167.33382956745544,
 181.09913246821685,
 199.26041948396235,
 225.03989356583492,
 264.3108002037564,
 337.1411969520337]
```

@Expertium, could you help me draw one with above data?

**Comment by Expertium** [comment]
You mean with colors? Ok, I'll do it later.

**Comment by L-M-Sherlock** [comment]
> You mean with colors? Ok, I'll do it later.

I mean the style of your original chart. Thanks!

**Comment by Expertium** [comment]
Is workload in minutes or reviews?

**Comment by L-M-Sherlock** [comment]
It's in minutes. However, it's better to keep the specific values hidden and only show the relative sizes on the chart.

**Comment by Expertium** [comment]
> It's in minutes. However, it's better to keep the specific values hidden and only show the relative sizes on the chart.

I agree about not showing exact values, but I think it's best to specify what units (time or reviews) is workload measured in

**Comment by Expertium** [comment]
Workload and retention, more accurate

**Comment by Expertium** [comment]
Oh, and I also recommend adding the add-on compatibility table to the second guide (about built-in FSRS) too.

**Comment by L-M-Sherlock** [comment]
Could you update this branch? I will merge it.

**Review by L-M-Sherlock — APPROVED** [review]

**Comment by L-M-Sherlock** [comment]
Oops. The chart seems misleading. Do you set the y axis' intercept to zero?

image

**Comment by Expertium** [comment]
What do you mean?

**Pull request merged**
