### PR TITLE
Make FSRS_status stay in position when scrolling

### PR DESCRIPTION
**Pull request by galantra**
A simple change so that the FSRS_status message is always displayed in the bottom left corner, keeping the same distance to the bottom bar, even after scrolling.

On cards that are long enough to scroll, it can incidentally also help with cases where the FSRS_status message and some card text overlap, like here:
image

I am not able to test or guess whether it is good on Anki Mobile. [edit: Though I could have investigated it on the forum and found [this thread by kleinerpirat](https://forums.ankiweb.net/t/ankimobile-issue-position-fixed-not-working-as-expected-solution/12100).]

### CODE REVIEW

**Comment by L-M-Sherlock** [comment]
Sadly, `position:absolute` and `position:fixed` both don't work in AnkiMobile.

**Comment by L-M-Sherlock** [comment]
How about it? Could you help me test it in your device?

**Comment by L-M-Sherlock** [comment]
image
https://forums.ankiweb.net/t/how-to-use-the-next-generation-spaced-repetition-algorithm-fsrs-on-anki/25415/57?u=l.m.sherlock

**Comment by galantra** [comment]
I'm testing it (including)e889e88acf04932e6931c5dcca8e146e31c48978) on my Windows 10; Anki Version ⁨2.1.57 (6b7d372c); Python 3.9.15 Qt 5.15.2 PyQt 5.15.5.  
(I cannot speak for iOS since I don't have an iOS device).

I will make another reply with my experiences with regard to scrolling, position and overlap.

**Review by L-M-Sherlock — APPROVED** [review]
Pass

**Comment by galantra** [comment]
# after https://github.com/open-spaced-repetition/fsrs4anki/commit/e889e88acf04932e6931c5dcca8e146e31c48978

## layout
Same as before (good).

## position

<details>
<summary>screenshot</summary>

image



</details>

Where it displays depends on the height of the card front. If the card is high enough, it is displayed below the card. If the card is not long enough, it is displayed at about the middle of the screen. 

In other words, the position is relative to the card content (not relative to the window as I tried to do it with `position:fixed`). However, it seems to hit some kind of ceiling beyond which it doesn't "move up" anymore.

## scrolling
As said, the position is relative to the card content, not the window. Therefore, it moves with the content when scrolling. I think this is great!

<details>
<summary>screenshot before</summary>

image


</details>

<details>
<summary>screenshot after</summary>

image


</details>

## overlap
There is no overlap anymore at all, great. Even better than `position:fixed` IMO, because `position:fixed` can temporarily still overlap with card content depending on the scroll bar position.

**Comment by galantra** [comment]
# after https://github.com/open-spaced-repetition/fsrs4anki/commit/f7bc5c9d7310fb566f8227dfbcd920524abf23ba

## layout

The line spacing is very large:

<details>
<summary>screenshot</summary>

image


</details>

## position

If the card has

```
.card {
 text-align: center;
}
```

then fsrs_status is centered, too:

<details>
<summary>screenshot</summary>

image

<sup>(I know, I know, this card is a leech.)</sup>

</details>

`text-align: center` is used by Basic cards and Image Occlusion, for example.

## scrolling

Same as before (good).

## overlap

Same as before (good).

**Comment by L-M-Sherlock** [comment]
> The line spacing is very large:

Because I replace the `div` with `span`. I have some overlapping case for `div`:

image

image

But the `line-height` seems doesn't seem to work for `span`. I don't know how to fix it.

**Comment by galantra** [comment]
I see, it's because I use 

```
.card {
 font-size: 3em;
}
```

in my card template CSS.

> But the line-height seems doesn't seem to work for span. I don't know how to fix it.

I've been trying to find a solution with the help of GPT-3, but to no avail so far.

For the time being, I will change it back to `div` in my Anki, since I haven't yet encountered the rightward shift in your screenshot.

**Pull request merged**
