### PR TITLE
Sort deckParams by length of deckName before looping through array

### PR DESCRIPTION
**Pull request by MNastri**
Minimal code for issue #168 

tested with an [online compiler](https://www.programiz.com/javascript/online-compiler/)  and seemed to work

    const deckParams = [
      {"deckName":"bbb"},
      {"deckName":"aaaa"},
      {"deckName":"cc"},
      {"deckName":"aabb"},
      {"deckName":"ccc"},
    ];
    
    function compareDeckNames(a, b) {
      // longer names come first, if equal length they will be ordered alphabetically
      if (a.deckName.length > b.deckName.length) {
        return -1;
      } else if (a.deckName.length < b.deckName.length) {
        return 1;
      } else {
        if (a.deckName < b.deckName) {
          return -1;
        } else if (a.deckName > b.deckName) {
          return 1;
        } else {
          return 0;
        }
      }
    }
    
    deckParams.sort(compareDeckNames);
    
    console.log(deckParams);

P.S.: It was just 1 commit I made but it is appearing as 11 commits. I don't know what is the issue...

### CODE REVIEW

**Comment by L-M-Sherlock** [comment]
> P.S.: It was just 1 commit I made but it is appearing as 11 commits. I don't know what is the issue...

Never mind it. The squash and merge could pack them into 1 commit.

**Comment by MNastri** [comment]
> > P.S.: It was just 1 commit I made but it is appearing as 11 commits. I don't know what is the issue...
> 
> Never mind it. The squash and merge could pack them into 1 commit.

Teach me the ways dude =)

**Comment by L-M-Sherlock** [comment]
> Teach me the ways dude =)

Only the reviewer could use it:

image

**Comment by L-M-Sherlock** [comment]
And I recommend syncing to my repo before you make a new pull request.

**Comment by L-M-Sherlock** [comment]
https://docs.github.com/en/get-started/quickstart/contributing-to-projects

It suggests developing the new feature in a new branch.

**Comment by L-M-Sherlock** [comment]
The code is a bit verbose. I make a simple version:

```javascript
const deckParams = [
  {"deckName":"aa"},
  {"deckName":"aa::aa"},
  {"deckName":"cc"},
  {"deckName":"cc::aa"},
  {"deckName":"cc::aa::bb"},
  {"deckName":"cc::dd::bb"},
];

deckParams.sort(function(a, b) {
  return -a.deckName.localeCompare(b.deckName);
});

console.log(deckParams);
```

**Pull request merged**
