### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by user1823**
I have made some edits to the README. I intend to do more edits when I get some more time. I am sharing this as a draft till then.

Comments and suggestions are welcome.

### CODE REVIEW

**Comment by L-M-Sherlock** [comment]
Please don't remove the logo of FSRS.

**Comment by user1823** [comment]
Ok, I have restored it.

**Review by Expertium — COMMENTED** [review]
I think it should be mentioned that 1000 reviews refers to reviews of cards that this preset is applied to.

**Comment by Expertium** [comment]
I forgot to include the interpetation of RMSE (bins). @user1823, I recommend including the following:
"Log-loss doesn't have an intuitive interpretation. RMSE (bins) can be interpeted as the average difference between the predicted probability of recalling a card (R) and the measured (from the user's review data) probability. For example, RMSE=0.05 means that, on average, FSRS is off by 5% when predicting R. Some users might see values as low as 1%, other users might see values as high as 10%."

**Comment by user1823** [comment]
This PR is ready for review now.

**Review by L-M-Sherlock — APPROVED** [review]
LGTM

**Pull request merged**
