### PR TITLE
Doc/native FSRS notification

### PR DESCRIPTION
**Pull request by L-M-Sherlock**
To welcome the release of Anki 23.10, I need to update the README. The main points are to remove the custom scheduling and update the helper add-on. And it would be helpful to write a new tutorial for the built-in FSRS. @Expertium, @user1823, what do you think of?

### CODE REVIEW

**Comment by Expertium** [comment]
Maybe make a separate readme for built-in FSRS? The old one will remain unchanged.

**Comment by L-M-Sherlock** [comment]
> The old one will remain unchanged.

It could confuse some users who find the link in our old post. At least, we need to notify these users that the custom scheduling will override the native FSRS.

**Comment by Expertium** [comment]
Ok, I'll submit a PR later

**Comment by user1823** [comment]
I agree with Expertium that we should create a separate tutorial for the native FSRS.

We can modify the current README by adding:

> ### Update
> 
> FSRS has been natively integrated into Anki 23.10. If you are using Anki 23.10+, refer to [this tutorial](link). If you are using an older version of Anki, continue reading ahead.

**Comment by Vilhelm-Ian** [comment]
Will this repo continue to develop after fsrs gets released in the official release. Or I will have to follow the commits on /ankitects repo to see how the scheduler continues to develop

**Comment by L-M-Sherlock** [comment]
> Will this repo continue to develop after fsrs gets released in the official release. Or I will have to follow the commits on /ankitects repo to see how the scheduler continues to develop

This repo doesn't develop the scheduler. It's a repo for the helper add-on. If you are interested in the repo of optimizer, you can see: https://github.com/open-spaced-repetition/fsrs-rs

**Pull request closed without merging**
