### PR TITLE
Fix/cut off incomplete revlogs in optimizer

### PR DESCRIPTION
**Pull request by L-M-Sherlock**

### CODE REVIEW

**Comment by user1823** [comment]
Does this patch include both of the patches you applied to the helper (https://github.com/open-spaced-repetition/fsrs4anki-helper/pull/51 and https://github.com/open-spaced-repetition/fsrs4anki-helper/pull/53)?

**Comment by user1823** [comment]
Could you also add [this patch](https://github.com/open-spaced-repetition/fsrs4anki-helper/pull/18/commits/b2d1eb31cf1460a33a46147233e2cd04d2877869) to the optimizer?

I know that this rule was modified later for the helper. But, for the optimizer, this version is better.

**Comment by user1823** [comment]
This patch also: https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/1471466fa603a703c9ce44cebb61f7278ddba24a

**Comment by L-M-Sherlock** [comment]
OK, thanks for reminding me. I will consider it in the optimizer.

**Comment by user1823** [comment]
> [open-spaced-repetition/fsrs4anki-helper@1471466](https://github.com/open-spaced-repetition/fsrs4anki-helper/commit/1471466fa603a703c9ce44cebb61f7278ddba24a)

Please add this patch also. Or, is it not required to add this patch to the optimizer (for e.g., if the optimizer already skips the cards without any revlogs)?

**Comment by L-M-Sherlock** [comment]
> Please add this patch also. Or, is it not required to add this patch to the optimizer (for e.g., if the optimizer already skips the cards without any revlogs)?

If the card doesn't have any revlogs, it would not appear in the revlog table.

**Pull request merged**
