### PR TITLE
Command line optimizer

### PR DESCRIPTION
**Pull request by Luc-mcgrady**
I moved all the functionality from the fsrs4anki_optimizer.ipynb to a class and then made a script which allows you to run the code that class from the command line rather than using the notebook. I also replaced the code in the notebook with calls to this class to prevent code duplication. 

This is useful if Google Colab prevents you from uploading files (which it does for me for some reason) and/or you have a lot of decks to optimize.

Having all the functionality in its own separate, run-able file might open the door to having the optimizer be part of the helper add-on although this would mean having torch installed locally on people computers and is probably why you opted for the the ipynb route in the first place.

### CODE REVIEW

**Comment by L-M-Sherlock** [comment]
Thanks for your contribution! I will review this PR tomorrow.

**Comment by L-M-Sherlock** [comment]
I encounter a problem. When I open the notebook in Colab and run the code, this error is raised: ModuleNotFoundError: No module named 'cmd_optimizer'. The colab only loads the .ipynb file.

**Comment by Luc-mcgrady** [comment]
I'm not very well experienced working with pip modules or Colab but I hope that helps.

**Comment by Luc-mcgrady** [comment]
Looks good to me
image
Do I add that line to the file or is that something you do with Colab?

**Comment by L-M-Sherlock** [comment]
I encountered a problem in Colab: 

```
Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 56.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 502.3/502.3 kB 36.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 887.5/887.5 MB 1.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 10.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 557.1/557.1 MB 2.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 849.3/849.3 kB 57.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.1/317.1 MB 4.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.0/21.0 MB 68.2 MB/s eta 0:00:00
  Building wheel for fsrs4anki_optimizer (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.15.1+cu118 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
torchtext 0.15.1 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
torchdata 0.6.0 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
torchaudio 2.0.1+cu118 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
tensorflow 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.24.3 which is incompatible.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.24.3 which is incompatible.
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem .
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-2-5b8239d912a1>](https://localhost:8080/#) in <cell line: 2>()
      1 get_ipython().run_line_magic('pip', "install -q 'fsrs4anki_optimizer @ git+https://github.com/Luc-mcgrady/fsrs4anki@command-line-optimizer#subdirectory=pip'")
----> 2 import fsrs4anki_optimizer as optimizer
      3 
      4 optimizer = optimizer.Optimizer()
      5 

9 frames
[/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py](https://localhost:8080/#) in <module>
     21 from numpy.core import(
     22      intp, float32, empty, arange, array_repr, ndarray, isnat, array)
---> 23 import numpy.linalg.lapack_lite
     24 
     25 from io import StringIO

ImportError: numpy.core.multiarray failed to import

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

**Comment by L-M-Sherlock** [comment]
Maybe we need to loosen the requirements.txt.

**Comment by Luc-mcgrady** [comment]
Ok, it works for me but only after I run `
Runtime>Restart runtime
`.  I'm not sure why that is or how to fix it.

**Comment by L-M-Sherlock** [comment]
It works well now. Could you help me to test it again?

**Comment by Luc-mcgrady** [comment]
Seems to work for me even without resetting the runtime 👍.
image

**Review by L-M-Sherlock — APPROVED** [review]

**Comment by L-M-Sherlock** [comment]
I make a pre-relesese: https://github.com/open-spaced-repetition/fsrs4anki/blob/v3.18.0/fsrs4anki_optimizer.ipynb.

**Pull request merged**
