### PR TITLE
A special case where "Ignore reviews before" won't work.md

### PR DESCRIPTION
**Pull request by Expertium**

### CODE REVIEW

**Comment by user1823** [comment]
> Would it be too much to ask people to hit "forget" on all their cards to generate more learning steps if changing their review habits?

Ideally, the users should NOT do this because the estimates of initial stability won't be accurate in that case (resetting the card in Anki doesn't delete the memories in the brain).

The ideal solution is that they continue to learn similar new cards. But, I know that this is not possible in every case. I don't know what's the best solution.

_Originally posted by @user1823 in https://github.com/ankitects/anki/issues/2922#issuecomment-1906105489_

**Comment by user1823** [comment]
Basically, in such cases, the user has to choose between two options:
1. Not using the `ignore reviews before` option and optimizing parameters using skewed review history
2. Using `Reset` and generating parameters with inaccurate initial stabilities.

I don't think that we should advice choosing one of these two. The option that is better for one user may not be better for another user.

**Comment by Expertium** [comment]
Yes, but we do have to advise _something_ that isn't "Keep seeing an error that says 0 reviews found"

**Comment by user1823** [comment]
I really don't know what to advise. Suggestions are welcome.

**Comment by Expertium** [comment]
I see 3 possibilities. The ones you mentioned + keep using the default parameters. Using the default parameters is probably worse than either of the two options, since the parameters won't be personalized at all. So we could advise users to choose option 1, we could advise users to choose option 2, or we could tell them about both options and let them choose, but that introduces an extra cognitive load, which isn't great. Honestly, I'm not sure myself.
@L-M-Sherlock what do you think?

**Comment by user1823** [comment]
By the way, there is a fourth option too. But, it is only for advanced users.

This option involves modifying the review history, as I advised a user here: https://github.com/open-spaced-repetition/fsrs4anki/issues/614#issuecomment-1962254401

**Comment by user1823** [comment]
> (option 0: rework this feature so that it actually ignores reviews, not cards)

This is not possible because the optimizer can't work on incomplete revlogs.

**Comment by Expertium** [comment]
But `memory_state_from_sm2` is a thing

**Comment by user1823** [comment]
> But `memory_state_from_sm2` is a thing

See https://github.com/open-spaced-repetition/fsrs-rs/issues/114

**Comment by Expertium** [comment]
I think the crux of the problem is that we can't quantify which of the 4 options - default parameters, Reset, optimize on bad review history, optimize while using `memory_state_from_sm2` - provides the best result. If we could rank these options somehow, we could say "Well, they're all bad, but this one is less bad, so let's go with the lesser evil".

**Comment by Expertium** [comment]
@L-M-Sherlock thoughts?

**Comment by L-M-Sherlock** [comment]
It's impossible to ignores reviews, not cards because reviews are also used to construct the training features.

**Comment by Expertium** [comment]
So what do we recommend to people who reviewed all cards before the selected date and do not plan to add new cards?

**Comment by L-M-Sherlock** [comment]
If they misused `hard` button, I remember that @user1823 provides a solution to modify the database. Maybe I can port it into the helper add-on.

**Comment by Expertium** [comment]
That's complicated, I wouldn't recommend that to everyone. We need something for an average user.

**Comment by L-M-Sherlock** [comment]
If I port it into the helper add-on, it will be very simple. Just click a button. And I think this case is rare. Maybe we cannot treat them as an average user.

**Review by L-M-Sherlock — APPROVED** [review]
LGTM

**Pull request merged**
