### PR TITLE
Feat/decouple user deck parameters from code

### PR DESCRIPTION
**Pull request by MNastri**
Pull request with the code (Qt5) for #149

### CODE REVIEW

**Comment by L-M-Sherlock** [comment]
Should we ask some users whether the new configuration is easier to understand than before?

**Comment by L-M-Sherlock** [comment]
I will release the new version of the scheduler after the helper add-on's release.

**Comment by MNastri** [comment]
> Should we ask some users whether the new configuration is easier to understand than before?

I don't think that's necessary because the code is easier to understand than before. 

Before this change, the data was inside the code and in the middle of it, but now it is outside the code and at the top of it. 
If they understood how to do it before they'll probably understand how to do it now.

**Comment by L-M-Sherlock** [comment]
I find out a bug: if the card's front doesn't include `<div id=deck deck_name="{{Deck}}"></div>`, the parameters will no be loaded.

https://github.com/MNastri/fsrs4anki/blob/c07e791b5255fffc4ce91d802f644152b73b8e75/fsrs4anki_scheduler_qt5.js#L73

**Comment by L-M-Sherlock** [comment]
What happened? I have fix the bug in last commit.

**Comment by MNastri** [comment]
my bad... I clicked to sync fork by mistake and didn't knew how to undo it... again, i'm sorry!

**Comment by L-M-Sherlock** [comment]
Mistake? Now the git prevents me from pushing my local code here......

**Comment by MNastri** [comment]
> Mistake? Now the git prevents me from pushing my local code here......
> 
> Fine. I will try to fix it.

I'm really sorry. I hope you can solve this. And please let me know if there's anything that I can do to help. 
It's just that I'm new to this whole open source collaboration and clicked 'sync fork' without reading/thinking enough.

**Pull request merged**
