### PR TITLE
Update tutorial.md

### PR DESCRIPTION
**Pull request by Expertium**

### CODE REVIEW

**Review by brishtibheja — COMMENTED** [review]
Hey, would be nice to also tell people this is currently being researched so that they don't jump to the conclusion there is some golden standard we already know?

**Comment by Expertium** [comment]
Ok, check the most recent commit

**Comment by brishtibheja** [comment]
Yeah that too. I was also talking about at which level optimisation should happen, the topic someone bought up today in the forums. Saying it depends on subjective difficulty will lead some people to believe we mean something very definite. Should be clear that it's still a very nebulous thing.

**Comment by Expertium** [comment]
I think you can propose changes yourself, though I'm not entirely sure how. I mean, without creating your own pull request, you can propose changes in mine

**Review by L-M-Sherlock — APPROVED** [review]

**Pull request merged**
