### PR TITLE
Ecosystem/decouple-optimizer-package

### PR DESCRIPTION
**Pull request by L-M-Sherlock**

### CODE REVIEW

**Comment by user1823** [comment]
After this change, where can I find the code of the optimizer?

**Comment by L-M-Sherlock** [comment]
Here: https://github.com/open-spaced-repetition/fsrs-optimizer

**Comment by cjdduarte** [comment]
What is this version? to run offline?

**Comment by L-M-Sherlock** [comment]
A python package for all FSRS implementations.

**Pull request merged**
