### PR TITLE
Update to FSRS-5

### PR DESCRIPTION
**Pull request by L-M-Sherlock**
Optimizer: https://colab.research.google.com/github/open-spaced-repetition/fsrs4anki/blob/update-to-FSRS-5/fsrs4anki_optimizer.ipynb

### CODE REVIEW

**Comment by brishtibheja** [comment]
Welcome, FSRS-5! Thanks for this, L.M.Sherlock ♥

**Comment by chrislongros** [comment]
There is a typo in the link for the custom scheduling script here: [https://github.com/open-spaced-repetition/fsrs4anki/releases/tag/v5.0.0](url)

**Comment by L-M-Sherlock** [comment]
Thanks, I have fixed it just now.

Yes, FSRS-5 considers the short term reviews, which will update the memory state.

**Comment by chrislongros** [comment]
When do you expect becoming stable, if you can estimate

**Comment by L-M-Sherlock** [comment]
I'm updating the built-in FSRS to v5, and it will take a week. But I don't know when the next release of Anki will be out.

You don't need to disable built-in FSRS.

**Comment by chrislongros** [comment]
Having const display_memory_state = true;
I see the stats of multiple cards that I reviewed before.

**Comment by L-M-Sherlock** [comment]
I can't reproduce this problem. Could you provide detail guide to reproduce it?

**Comment by chrislongros** [comment]
I run the latest git version of Anki repo. I have FSRS enabled and copied the custom FSRS-5 scheduler to the appropriate box. Set the max interval at 90 and the "display memory state" variable to true. I do my reviews from a filtered deck. The first card shows the memory state at the bottom. After reviewing the next cards it shows multiple boxes with memory states of what I assume to be other cards.

**Comment by chrislongros** [comment]
The problem appears only with FSRS Helper addon. When I disable all the addons it shows normally.

**Comment by L-M-Sherlock** [comment]
I guess you enable the add-on's display_memory_state?

**Comment by chrislongros** [comment]
Oh yeah, I disabled it and it now runs as expected...

**Comment by abdmohrat** [comment]
I pasted the schedular to custom scheduling and updated my parameters, but it does not seem to affect the collection. The helper addon is rescheduling the cards based on the built in FSRS not the one in custom scheduling. I tried changing the retention rate in custom scheduling but this does not change anything, while changing the retention rate in the built in FSRS does change the review amount.
displaying the memory state from the custom schedular is working.
I am using the latest version of Anki and the helper addon as well.

**Comment by brishtibheja** [comment]
The rescheduling isn't happening based on what's inside 'custom scheduling' might be more of a helper add-on "issue" rather than of FSRS-5.

**Comment by jjy1000** [comment]
1.我更新了自定义排程FSRS5，也在使用FSRSanki的插件，我不知道这两个之间是否相冲突，因为我并没有选择改动anki中插件选项，例如重新安排负载平衡之类的选项，不知道这是否阻碍自定义排程的运转？
2.不知道何时能在anki插件中实现5的更新？
3.一直有个疑惑，在我卡组多的时候，卡片也随之增加，不知道FSRS是否会整体考虑卡片的总数量，例如每天学习的记忆负荷压力，毕竟随着知识卡片的不断累积，每天需要复习卡片总数量的也在增加。
4.考虑过能够实现商业付费？毕竟有时候付费能够支持该项目的持续和运转

**Comment by L-M-Sherlock** [comment]
@jjy1000 

1. 两个不冲突
2. 得等 Anki 内置 FSRS-5
3. 你学的新卡片多，复习量自然会增加，和你牌组数量多寡并无关系
4. 不考虑，收费了我就要承担很多责任，现在我随时都可以不干了

**Pull request merged**
